const os = require('os')
console.log('Operating System Info...')

console.log(`Platform ${os.platform()}`)
console.log(`Architecture ${os.arch()}`)
console.log(`CPU Cores ${os.cpus().length}`)
console.log(`Total Memory ${(os.totalmem() / (1024 ** 3)).toFixed(2)} GB `)
console.log(`Free Memory ${(os.freemem()  / (1024 ** 3)).toFixed(2)} GB )}`)
console.log(`Home Directory ${os.homedir()}`)
console.log(`Uptime ${(os.uptime() / 3600).toFixed(2)} Hours`)
console.log(`Hostname ${os.hostname()}`)
console.log(`Machine Type ${os.machine()}`)
console.log(`User Info ${JSON.stringify(os.userInfo())}`)
console.log(`Temp Directory ${os.tmpdir()}`)
console.log(`Network Interface ${JSON.stringify(os.networkInterfaces(), null, 2)}`)